### ISSUE TITLE
perform a wait of export processing

### ISSUE THREAD

**Issue by MSakamaki** [club-wot/WebGPIO#18]
- [x] `navigator.mozGpio.export(data.portNumber);`の完了がわかるようにする。
- [x] gpioのexport時にi2c用portをexportしないように変更
- [x] pullrequest#20の取り込み

**Comment by MSakamaki** [comment]
とりあえず、gpioのexportを直列に行うように修正

**Comment by MSakamaki** [comment]
新しい問題が発生したのそちらも対応

> polyfillを使ってonchangeイベントを扱うと、タクトスイッチを押した時にonchangeイベントが2回発生することがありますね

**Comment by naokisekiguchi** [comment]
webgpio.jsとwebi2c.jsを両方読み込むと、それぞれでworkerを登録するためにonchangeイベントが2回発生するようです。webgpio.jsだけ読み込むようにしたらonchangeイベントは１回だけ発生するようになりました。

**Comment by naokisekiguchi** [comment]
上記に加え、webgpio.jsにて、I2Cに使われているポート（253,252,256,257）もexportしているため、gpioとI2Cの同時利用ができない状態になっています。
PORT_CONFIGの該当箇所をコメントアウトすること、worker登録の共通部分を除きwebgpio.jsとwebi2c.jsをマージすることで、動作することを確認しました。

**Comment by MSakamaki** [comment]
done.
